Add linter configuration
sighupio/fip-healthcheck-go-template pull request #5
Opened 2021-07-01 11:28 UTC by angelbarrera92

With this PR I am trying to address an extended configuration of the linters.

- golang-ci: I've configured a more strict behaviour with the limitations that the `policeman`/`super-linter` runs in a single file mode. As an example, with the previous config was an issue with private functions invocation from the same package.
- jscpd: Checks for copy/pastes. I configured it to exclude markdown files and go `test` files. 

Thanks!

2021-07-02 08:16 UTC, nandajavarma commented on .rules/.jscpd.json
> +    "/**/**.md"
should we ignore markdown linting? :)

2021-07-02 08:16 UTC, nandajavarma commented on .rules/.jscpd.json
> +    "/**/**.md"
might be useful for consistency when we (hopefully) automate doc building from markdowns.

2021-07-02 10:36 UTC, angelbarrera92 commented on .rules/.jscpd.json
> +    "/**/**.md"
It just avoids the "copy/paste" linter: https://github.com/kucherenko/jscpd
There are multiple false positive so i think the honest action is to deactivate just this linter on markdown files

2021-07-06 11:29 UTC, nandajavarma commented on .rules/.golangci.yml
> -    - golint
I see that golint has been replaced by revive. Should we add that too?

2021-07-06 11:31 UTC, nandajavarma requested changes
Working good in my local.  I would say mergeable.

2021-07-06 11:31 UTC, nandajavarma approved these changes

2021-07-06 11:35 UTC, angelbarrera92 commented on .rules/.golangci.yml
> -    - golint
Checking the following list: https://github.com/golangci/golangci-lint/issues/1574#issuecomment-804500358 seems like revive works in single file mode. Let me test it :)

2021-07-06 11:39 UTC, angelbarrera92 commented on .rules/.golangci.yml
> -    - golint
Added!

2021-07-06 11:42 UTC, merged